version: '3.8'

networks:
  starter:

services:
  starter-db:
    image: mysql:8.0
    env_file:
      - ./docker/mysql.env
    container_name: 'starter-db'
    restart: 'no'
    ports:
      - 5306:3306
    volumes:
      - ./docker/conf/mysql.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./docker/data:/var/lib/mysql
      - ./docker/logs:/var/log/mysql
    networks:
      - starter
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
